### ISSUE TITLE
Not building

### ISSUE THREAD

**Issue by hugocore** [proofpoint/kairos-announce#1]
I just tried to build your plugin with a fresh clone and it's not building. I guess it's some sort of dependencies problem.
I followed the instruction in the "how_to_build.txt" file:
1. $ git clone https://github.com/proofpoint/kairos-announce.git
Cloning into 'kairos-announce-plugin'...
...
Unpacking objects: 100% (65/65), done.
2. $ export CLASSPATH=tools/tablesaw-1.0.2.jar
3. java make
Compiling 2 source files.
warning: [options] bootstrap class path not set in conjunction with -source 1.6
src\main\java\org\kairosdb\plugin\announce\AnnounceModule.java:20: error: package com.google.inject does not exist
import com.google.inject.AbstractModule;
                        ^
src\main\java\org\kairosdb\plugin\announce\AnnounceModule.java:21: error: package com.google.inject does not exist
import com.google.inject.Singleton;
                        ^
src\main\java\org\kairosdb\plugin\announce\AnnounceModule.java:23: error: cannot find symbol
public class AnnounceModule extends AbstractModule
                                    ^
  symbol: class AbstractModule
src\main\java\org\kairosdb\plugin\announce\AnnounceService.java:19: error: package com.google.inject.name does not exist
import com.google.inject.name.Named;
                             ^
src\main\java\org\kairosdb\plugin\announce\AnnounceService.java:20: error: package org.apache.http does not exist
import org.apache.http.HttpResponse;
                      ^
src\main\java\org\kairosdb\plugin\announce\AnnounceService.java:21: error: package org.apache.http.client does not exist
import org.apache.http.client.HttpClient;

and the list goes on..
I even tried to do "java make ivy-resolve" and repeat the process, but without effect.
Did you do something additional to build this plugin?

Thanks for the input
Best regards

**Comment by brianhks** [comment]
You must not have set the KAIROS property.  The build script should have complained that it wasn't set.  In my case I ran this

> export KAIROS=/home/bhawkins/programs/kairosdb/

Just to clarify that KAIROS points to a deployed kairosdb location ie. if you download the tar.gz version of kairos and extract it then the root folder is where you set KAIROS to.  The build script will add $KAIROS/lib/*.jar to the classpath when building.

Yes I understand this is a poopy way of creating plugins.  I'm working on a strategy to make it a lot easier.
